model a2.mod ;
data real_example/real1/X.dat ;
data real_example/real1/Z1.dat ;
data real_example/real1/A1.dat ;
data real_example/real1/Z2.dat ;
data real_example/real1/A2.dat ;
data weight/ampl_bias_1.dat ;
data weight/ampl_bias_2.dat ;
data weight/ampl_weight_1.dat ;
data weight/ampl_weight_2.dat ;
option solver "/home/aheirich/bin/ampl.linux64/knitro" ;
option knitro_options 'outlev=3';
option presolve 0 ;
option show_stats 1 ;
solve ;

